site_name: Universal_hal
plugins:
  - mkdoxy:
      projects:
        atmelsam_i2c_host/:
          src-dirs: "hal/ hal/platform/atmelsam/"
          full-doc: True
          doxy-cfg:
            FILE_PATTERNS: "i2c.c 
            				i2c_platform_specific.h 
            				peripheral_clocking.h 
            				sercom_stuff.h 
            				default_isr_handlers.h 
            				default_irq_handlers.c
            				hal_i2c_host.h"
            RECURSIVE: False
            EXTRACT_ALL: True
markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc
  - tables
  - admonition
  - pymdownx.superfences:
     custom_fences:
         - name: mermaid
           class: mermaid
           format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true 
  - def_list
  - tables
  - pymdownx.blocks.admonition:
      types:
      - new
      - settings
      - note
      - abstract
      - info
      - tip
      - success
      - question
      - warning
      - failure
      - danger
      - bug
      - example
      - quote
theme:
    name: material
    logo: assets/Universal_hal_logo_top_bar.svg
    favicon: assets/Universal_hal_logo_top_bar.svg
    palette: 
    # Palette toggle for light mode
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
features:
  - content.tabs.link
extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home: "index.md"
  - API:
      - 'GPIO':
        - 'Compatibility': "API/GPIO/gpio_compatibility.md"
        - 'General API': "API/GPIO/gpio_api.md"
        - 'API platform':
           - SAMD:
             - "About": API/GPIO/platform/atmelsam/about.md
      - 'I2C Host':
        - 'Compatibility': "API/I2C_host/i2c_compatibility.md"
        - 'General API': "API/I2C_host/i2c_host_api.md"
        - 'API platform':
           - SAMD:
             - "About": API/I2C_host/platform/atmelsam/about.md
             - "Usage": API/I2C_host/platform/atmelsam/Usage.md
             - "Critical Notes": API/I2C_host/platform/atmelsam/Critical_notes.md
             - Doxygen:
               - "Struct List": "atmelsam_i2c_host/annotated.md"
               - "Struct Member Variables": "atmelsam_i2c_host/class_member_variables.md"
               - "Functions": "atmelsam_i2c_host/functions.md"
               - "Variables": "atmelsam_i2c_host/variables.md"
               - "Macros": "atmelsam_i2c_host/macros.md"
               - "Files": "atmelsam_i2c_host/files.md"
      - 'I2C Slave':
        - 'Compatibility': "API/I2C_slave/i2c_compatibility.md"
        - 'General API': "API/I2C_slave/i2c_slave_api.md"
        - 'API platform':
           - SAMD:
             - "About": API/I2C_slave/platform/atmelsam/About.md
             - "Usage": API/I2C_slave/platform/atmelsam/Usage.md
             - "Critical Notes": API/I2C_slave/platform/atmelsam/Critical_notes.md
      - 'SPI Host':
        - 'Compatibility': "API/SPI_host/spi_host_compatibility.md"
        - 'General API': "API/SPI_host/spi_host_api.md"
        - 'API platform':
           - SAMD:
             - "About": API/SPI_host/platform/atmelsam/About.md
             - "Usage": API/SPI_host/platform/atmelsam/Usage.md
             - "Critical Notes": API/SPI_host/platform/atmelsam/Critical_notes.md
      - 'SPI Slave':
        - 'Compatibility': "API/SPI_slave/spi_slave_compatibility.md"
        - 'General API': "API/SPI_slave/spi_slave_api.md"
        - 'API platform':
           - SAMD:
             - "About": API/SPI_slave/platform/atmelsam/About.md
             - "Usage": API/SPI_slave/platform/atmelsam/Usage.md
             - "Critical Notes": API/SPI_slave/platform/atmelsam/Critical_notes.md
      - 'UART':
        - 'Compatibility': "API/UART/uart_compatibility.md"
        - 'General API': "API/UART/uart_api.md"
        - 'API platform':
           - SAMD:
             - "About": API/UART/platform/atmelsam/About.md
             - "Usage": API/UART/platform/atmelsam/Usage.md
             - "Critical Notes": API/UART/platform/atmelsam/Critical_notes.md
      - 'DMA':
        - 'Compatibility': "API/DMA/dma_compatibility.md"
        - 'General API': "API/DMA/dma_api.md"
        - 'API platform':
           - SAMD:
             - "About": API/DMA/platform/atmelsam/About.md
             - "Usage": API/DMA/platform/atmelsam/Usage.md
             - "Critical Notes": API/DMA/platform/atmelsam/Critical_notes.md
  - Contributing:
    - 'General': 'contributing.md'
    - 'Code style': 'code_style.md'

